countries = {
				'afghanistan':["Afghanistan","afghanistan","AFGHANISTAN","Afganistán","Afghanistan","afghanistan","Afghanistan"],
				'ala':["aland-islands","ALA Aland Islands","ala aland islands","ALA ALAND ISLANDS","ALA Islas Aland","ALA Îles Aland","ALA Isole Aland","ALA Aland Islands"],
				'albania':["Albania","albania","ALBANIA","Albania","Albanie","Albania","Albanien"],
				'algeria':["Algeria","algeria","ALGERIA","Argelia","Algérie","algeria","Algerien"],
				'american':["samoa","American Samoa","american samoa","AMERICAN SAMOA","Samoa Americana","Samoa américaines","Samoa americane","Amerikanischen Samoa-Inseln"],
				'andorra':["Andorra","andorra","ANDORRA","Andorra","Andorre","Andorra","Andorra"],
				'angola':["Angola","angola","ANGOLA","Angola","Angola","angola","Angola"],
				'anguilla':["Anguilla","anguilla","ANGUILLA","Anguilla","Anguilla","Anguilla","Anguilla"],
				'antarctica':["Antarctica","antarctica","ANTARCTICA","Antártida","Antarctique","Antartide","Antarktika"],
				'antigua':["and-barbuda","Antigua and Barbuda","antigua and barbuda","ANTIGUA AND BARBUDA","Antigua y Barbuda","Antigua-et-Barbuda","Antigua e Barbuda","Antigua und Barbuda"],
				'argentina':["Argentina","argentina","ARGENTINA","Argentina","Argentine","Argentina","Argentinien"],
				'armenia':["Armenia","armenia","ARMENIA","Armenia","Arménie","Armenia","Armenien"],
				'aruba':["Aruba","aruba","ARUBA","Aruba","Aruba","aruba","Aruba"],
				'australia':["Australia","australia","AUSTRALIA","Australia","Australie","Australia","Australien"],
				'austria':["Austria","austria","AUSTRIA","Austria',L'Autriche","Austria","Österreich"],
				'azerbaijan':["Azerbaijan","azerbaijan","AZERBAIJAN","Azerbaiyán","Azerbaïdjan","Azerbaijan","Aserbaidschan"],
				'bahamas':["Bahamas","bahamas","BAHAMAS","Bahamas","Bahamas","Bahamas","Bahamas"],
				'bahrain':["Bahrain","bahrain","BAHRAIN","Bahrein","Bahreïn","Bahrain","Bahrein"],
				'bangladesh':["Bangladesh","bangladesh","BANGLADESH","Bangladesh","Bangladesh","Bangladesh","Bangladesch"],
				'barbados':["Barbados","barbados","BARBADOS","Barbados","Barbade","Barbados","Barbados"],
				'belarus':["Belarus","belarus","BELARUS","Bielorrusia","Biélorussie","Bielorussia","Weißrussland"],
				'belgium':["Belgium","belgium","BELGIUM","Bélgica","Belgique","Belgio","Belgien"],
				'belize':["Belize","belize","BELIZE","Belice","Belize","Belize","Belize"],
				'benin':["Benin","benin","BENIN","Benin","Bénin","Benin","Benin"],
				'bermuda':["Bermuda","bermuda","BERMUDA","islas Bermudas","Bermudes","Bermuda","Bermuda"],
				'bhutan':["Bhutan","bhutan","BHUTAN","Bután","Bhoutan","Bhutan","Bhutan"],
				'bolivia':["Bolivia","bolivia","BOLIVIA","Bolivia","Bolivie","Bolivia","Bolivien"],
				'bosnia':["and-herzegovina","Bosnia and Herzegovina","bosnia and herzegovina","BOSNIA AND HERZEGOVINA","Bosnia y Herzegovina","Bosnie Herzégovine","Bosnia Erzegovina","Bosnien und Herzegowina"],
				'botswana':["Botswana","botswana","BOTSWANA","Botswana","Botswana","Botswana","Botswana"],
				'bouvet':["island","Bouvet Island","bouvet island","BOUVET ISLAND","Isla Bouvet","Île Bouvet","Isola Bouvet","Bouvet-Insel"],
				'brazil':["Brazil","brazil","BRAZIL","Brasil","Brésil","Brasile","Brasilien"],
				'british':["indian-ocean-territory","British Indian Ocean Territory","british indian ocean territory","BRITISH INDIAN OCEAN TERRITORY","Territorio Británico del Océano Índico","Territoire britannique de l'océan Indien","Territorio britannico dell'Oceano Indiano","Britisches Territorium des Indischen Ozeans"],
				'british':["virgin-islands","British Virgin Islands","british virgin islands","BRITISH VIRGIN ISLANDS","Islas Vírgenes Británicas","Îles Vierges britanniques","Isole Vergini Britanniche","Britische Jungferninseln"],
				'brunei':["Brunei Darussalam","brunei darussalam","BRUNEI DARUSSALAM","Brunei Darussalam","Brunei Darussalam","Brunei Darussalam","Brunei Darussalam"],
				'bulgaria':["Bulgaria","bulgaria","BULGARIA","Bulgaria","Bulgarie","Bulgaria","Bulgarien"],
				'burkina':["faso","Burkina Faso","burkina faso","BURKINA FASO","Burkina Faso","Burkina Faso","Burkina Faso","Burkina Faso"],
				'burundi':["Burundi","burundi","BURUNDI","Burundi","Burundi","Burundi","Burundi"],
				'cambodia':["Cambodia","cambodia","CAMBODIA","Camboya","Cambodge","Cambogia","Kambodscha"],
				'cameroon':["Cameroon","cameroon","CAMEROON","Camerún","Cameroun","Camerun","Kamerun"],
				'canada':["Canada","canada","CANADA","Canadá","Canada","Canada","Kanada"],
				'cape':["verde","Cape Verde","cape verde","CAPE VERDE","Cabo Verde","Cap-Vert","capo Verde","Kap Verde"],
				'cayman':["islands","Cayman Islands","cayman islands","CAYMAN ISLANDS","Islas Caimán","Îles Caïmans","Isole Cayman","Cayman Inseln"],
				'central':["african-republic","Central African Republic","central african republic","CENTRAL AFRICAN REPUBLIC","República Centroafricana","République centrafricaine","Repubblica Centrafricana","Zentralafrikanische Republik"],
				'chad':["Chad","chad","CHAD","Chad","Tchad","Chad","Tschad"],
				'chile':["Chile","chile","CHILE","Chile","Chili","Chile","Chile"],
				'china':["China","china","CHINA","China","Chine","Cina","China"],
				'christmas':["island","Christmas Island","christmas island","CHRISTMAS ISLAND","Isla de Navidad","L'île de noël","Isola di Natale","Weihnachtsinsel"],
				'cocos':["keeling-islands","Cocos (Keeling) Islands","cocos (keeling) islands","COCOS (KEELING) ISLANDS","Cocos (Keeling)","Îles Cocos (Keeling)","Cocos (Keeling)","Cocos (Keeling) Islands"],
				'colombia':["Colombia","colombia","COLOMBIA","Colombia","Colombie","Colombia","Kolumbien"],
				'comoros':["Comoros","comoros","COMOROS","Comoras","Comores","Comoros","Komoren"],
				'congo':["brazzaville","Congo (Brazzaville)","congo (brazzaville)","CONGO (BRAZZAVILLE)","Congo (Brazzaville)","Congo (Brazzaville)","Congo (Brazzaville)","Kongo (Brazzaville)"],
				'congo':["kinshasa","Congo (Kinshasa)","congo (kinshasa)","CONGO (KINSHASA)","Congo (Kinshasa)","Congo (Kinshasa)","Congo (Kinshasa)","Kongo (Kinshasa)"],
				'cook':["islands","Cook Islands","cook islands","COOK ISLANDS","Islas Cook","les Îles Cook","Isole Cook","Cookinseln"],
				'costa':["rica","Costa Rica","costa rica","COSTA RICA","Costa Rica","Costa Rica","Costa Rica","Costa Rica"],
				'cote':["divoire","Côte d'Ivoire","côte d'ivoire","CÔTE D'IVOIRE","Costa de Marfil","Côte d'Ivoire","Costa d'Avorio","Côte d'Ivoire"],
				'croatia':["Croatia","croatia","CROATIA","Croacia","Croatie","Croazia","Kroatien"],
				'cuba':["Cuba","cuba","CUBA","Cuba","Cuba","Cuba","Kuba"],
				'cyprus':["Cyprus","cyprus","CYPRUS","Chipre","Chypre","Cipro","Zypern"],
				'czech':["republic","Czech Republic","czech republic","CZECH REPUBLIC","Republica checa","République Tchèque","Repubblica Ceca","Tschechien"],
				'denmark':["Denmark","denmark","DENMARK","Dinamarca","Danemark","Danimarca","Dänemark"],
				'djibouti':["Djibouti","djibouti","DJIBOUTI","Djibouti","Djibouti","Gibuti","Dschibuti"],
				'dominica':["Dominica","dominica","DOMINICA","dominica","Dominique","Dominica","Dominica"],
				'dominican':["republic","Dominican Republic","dominican republic","DOMINICAN REPUBLIC","República Dominicana","République Dominicaine","Repubblica Dominicana","Dominikanische Republik"],
				'ecuador':["Ecuador","ecuador","ECUADOR","Ecuador","Equateur","Ecuador","Ecuador"],
				'egypt':["Egypt","egypt","EGYPT","Egipto","Egypte","Egitto","Ägypten"],
				'el':["salvador","El Salvador","el salvador","EL SALVADOR","El Salvador","Le Salvador","El Salvador","El Salvador"],
				'equatorial':["guinea","Equatorial Guinea","equatorial guinea","EQUATORIAL GUINEA","Guinea Ecuatorial","Guinée Équatoriale","Guinea Equatoriale","Äquatorialguinea"],
				'eritrea':["Eritrea","eritrea","ERITREA","Eritrea","Érythrée","l'Eritrea","Eritrea"],
				'estonia':["Estonia","estonia","ESTONIA","Estonia","Estonie","Estonia","Estland"],
				'ethiopia':["Ethiopia","ethiopia","ETHIOPIA","Etiopía","Ethiopie","Etiopia","Äthiopien"],
				'falkland':["islands-malvinas","Falkland Islands (Malvinas)","falkland islands (malvinas)","FALKLAND ISLANDS (MALVINAS)","Islas Malvinas (Falkland)","Îles Falkland (Malvinas)","Isole Falkland (Malvinas)","Falklandinseln (Malvinas)"],
				'faroe':["islands","Faroe Islands","faroe islands","FAROE ISLANDS","Islas Faroe","Îles Féroé","Isole Faroe","Färöer Inseln"],
				'fiji':["Fiji","fiji","FIJI","Fiji","Fidji","Fiji","Fidschi"],
				'finland':["Finland","finland","FINLAND","Finlandia","Finlande","Finlandia","Finnland"],
				'france':["France","france","FRANCE","Francia","France","Francia","Frankreich"],
				'french':["guiana","French Guiana","french guiana","FRENCH GUIANA","Guayana francés","Guyane Française","Guiana francese","Französisch-Guayana"],
				'french':["polynesia","French Polynesia","french polynesia","FRENCH POLYNESIA","Polinesia francés","Polynésie française","Polinesia francese","Französisch Polynesien"],
				'french':["southern-territories","French Southern Territories","french southern territories","FRENCH SOUTHERN TERRITORIES","Territorios Franceses del Sur","Terres australes françaises","Territori della Francia del sud","Südfranzösische Territorien"],
				'gabon':["Gabon","gabon","GABON","Gabón","Gabon","Gabon","Gabun"],
				'gambia':["Gambia","gambia","GAMBIA","Gambia","Gambie","Gambia","Gambia"],
				'georgia':["Georgia","georgia","GEORGIA","Georgia","Géorgie","Georgia","Georgia"],
				'germany':["Germany","germany","GERMANY","Alemania","Allemagne","Germania","Deutschland"],
				'ghana':["Ghana","ghana","GHANA","Ghana","Ghana","Ghana","Ghana"],
				'gibraltar':["Gibraltar","gibraltar","GIBRALTAR","Gibraltar","Gibraltar","Gibilterra","Gibraltar"],
				'greece':["Greece","greece","GREECE","Grecia","Grèce","Grecia","Griechenland"],
				'greenland':["Greenland","greenland","GREENLAND","Groenlandia","Groenland","Groenlandia","Grönland"],
				'grenada':["Grenada","grenada","GRENADA","Granada","Grenade","Grenada","Grenada"],
				'guadeloupe':["Guadeloupe","guadeloupe","GUADELOUPE","Guadalupe","Guadeloupe","Guadeloupe","Guadeloupe"],
				'guam':["Guam","guam","GUAM","Guam","Guam","Guam","Guam"],
				'guatemala':["Guatemala","guatemala","GUATEMALA","Guatemala","Guatemala","Guatemala","Guatemala"],
				'guernsey':["Guernsey","guernsey","GUERNSEY","Guernesey","Guernesey","maglione","Guernsey"],
				'guinea':["Guinea","guinea","GUINEA","Guinea","Guinée","Guinea","Guinea"],
				'guinea':["bissau","Guinea-Bissau","guinea-bissau","GUINEA-BISSAU","Guinea-Bissau","Guinée-Bissau","Guinea-Bissau","Guinea-Bissau"],
				'guyana':["Guyana","guyana","GUYANA","Guayana","Guyane","Guyana","Guyana"],
				'haiti':["Haiti","haiti","HAITI","Haití","Haïti","Haiti","Haiti"],
				'heard':["and-mcdonald-islands","Heard and Mcdonald Islands","heard and mcdonald islands","HEARD AND MCDONALD ISLANDS","Islas Heard y McDonald","Îles Heard et Mcdonald","Heard e McDonald","Heard und McDonald-Inseln"],
				'holy':["see-vatican-city-state","Holy See (Vatican City State)","holy see (vatican city state)","HOLY SEE (VATICAN CITY STATE)","Santa Sede (Ciudad del Vaticano)","Saint-Siège (Cité du Vatican)","Santa Sede (Città del Vaticano)","Heiliger Stuhl (Vatikanstadt)"],
				'honduras':["Honduras","honduras","HONDURAS","Honduras","Honduras","Honduras","Honduras"],
				'hong':["kong-sar-china","Hong Kong","hong kong","HONG KONG","Hong Kong","Hong Kong","Hong Kong","Hongkong"],
				'hungary':["Hungary","hungary","HUNGARY","Hungría","Hongrie","Ungheria","Ungarn"],
				'iceland':["Iceland","iceland","ICELAND","Islandia","Islande","Islanda","Island"],
				'india':["India","india","INDIA","India","Inde","India","Indien"],
				'indonesia':["Indonesia","indonesia","INDONESIA","Indonesia","Indonésie","Indonesia","Indonesien"],
				'iran':["Iran","iran","IRAN","Irán","L'Iran","Iran","Iran"],
				'iraq':["Iraq","iraq","IRAQ","Irak","Irak","Iraq","Irak"],
				'ireland':["Ireland","ireland","IRELAND","Irlanda","Irlande","Irlanda","Irland"],
				'isle':["of-man","Isle of Man","isle of man","ISLE OF MAN","Isla del hombre","île de Man","Isola di Man","Isle of Man"],
				'israel':["Israel","israel","ISRAEL","Israel","Israël","Israele","Israel"],
				'italy':["Italy","italy","ITALY","Italia","Italie","Italia","Italien"],
				'jamaica':["Jamaica","jamaica","JAMAICA","Jamaica","Jamaïque","Giamaica","Jamaika"],
				'japan':["Japan","japan","JAPAN","Japón","Japon","Giappone","Japan"],
				'jersey':["Jersey","jersey","JERSEY","Jersey","Jersey","maglia","Jersey"],
				'jordan':["Jordan","jordan","JORDAN","Jordán","Jordan","Giordania","Jordanien"],
				'kazakhstan':["Kazakhstan","kazakhstan","KAZAKHSTAN","Kazajstán","Kazakhstan","Kazakistan","Kasachstan"],
				'kenya':["Kenya","kenya","KENYA","Kenia","Kenya","Kenia","Kenia"],
				'kiribati':["Kiribati","kiribati","KIRIBATI","Kiribati","Kiribati","Kiribati","Kiribati"],
				'korea':["north","Korea (North)","korea (north)","KOREA (NORTH)","Corea (del Norte)","Corée (du Nord)","Corea (Nord)","Korea (Nord)"],
				'korea':["south","Korea (South)","korea (south)","KOREA (SOUTH)","Corea del Sur","COREE DU SUD","Corea del Sud","Korea"," Süden"],
				'kuwait':["Kuwait","kuwait","KUWAIT","Kuwait","Koweit","Kuwait","Kuwait"],
				'kyrgyzstan':["Kyrgyzstan","kyrgyzstan","KYRGYZSTAN","Kirguizistán","Kirghizistan","Kyrgyzstan","Kirgisistan"],
				'lao':["pdr","Lao PDR","lao pdr","LAO PDR","República Democrática Popular Lao","République démocratique populaire lao","Lao PDR","Laos"],
				'latvia':["Latvia","latvia","LATVIA","Letonia","Lettonie","Lettonia","Lettland"],
				'lebanon':["Lebanon","lebanon","LEBANON","Líbano","Liban","Libano","Libanon"],
				'lesotho':["Lesotho","lesotho","LESOTHO","Lesoto","Lesotho","Lesoto","Lesotho"],
				'liberia':["Liberia","liberia","LIBERIA","Liberia","Libéria","Liberia","Liberia"],
				'libya':["Libya","libya","LIBYA","Libia","Libye","Libia","Libyen"],
				'liechtenstein':["Liechtenstein","liechtenstein","LIECHTENSTEIN","Liechtenstein","Liechtenstein","Liechtenstein","Liechtenstein"],
				'lithuania':["Lithuania","lithuania","LITHUANIA","Lituania","Lituanie","Lituania","Litauen"],
				'luxembourg':["Luxembourg","luxembourg","LUXEMBOURG","Luxemburgo","Luxembourg","Lussemburgo","Luxemburg"],
				'macao':["sar-china","Macao","macao","MACAO","macao","Macao","Macao","Macao"],
				'macedonia':["Macedonia","macedonia","MACEDONIA","macedonia","Macédoine","Macedonia","Mazedonien"],
				'madagascar':["Madagascar","madagascar","MADAGASCAR","Madagascar","Madagascar","Madagascar","Madagaskar"],
				'malawi':["Malawi","malawi","MALAWI","Malawi","Malawi","Malawi","Malawi"],
				'malaysia':["Malaysia","malaysia","MALAYSIA","Malasia","Malaisie","Malaysia","Malaysia"],
				'maldives':["Maldives","maldives","MALDIVES","Maldivas","Maldives","Maldive","Malediven"],
				'mali':["Mali","mali","MALI","mali","Mali","Mali","Mali"],
				'malta':["Malta","malta","MALTA","Malta","Malte","Malta","Malta"],
				'marshall':["islands","Marshall Islands","marshall islands","MARSHALL ISLANDS","Islas Marshall","Iles Marshall","Isole Marshall","Marshallinseln"],
				'martinique':["Martinique","martinique","MARTINIQUE","Martinica","Martinique","Martinique","Martinique"],
				'mauritania':["Mauritania","mauritania","MAURITANIA","Mauritania","Mauritanie","Mauritania","Mauretanien"],
				'mauritius':["Mauritius","mauritius","MAURITIUS","Isla mauricio","Ile Maurice","Mauritius","Mauritius"],
				'mayotte':["Mayotte","mayotte","MAYOTTE","Mayotte","Mayotte","Mayotte","Mayotte"],
				'mexico':["Mexico","mexico","MEXICO","México","Mexique","Messico","Mexiko"],
				'micronesia':["Micronesia","micronesia","MICRONESIA","micronesia","Micronésie","Micronesia","Mikronesien"],
				'moldova':["Moldova","moldova","MOLDOVA","Moldavia","Moldavie","Moldova","Moldawien"],
				'monaco':["Monaco","monaco","MONACO","Mónaco","Monaco","Monaco","Monaco"],
				'mongolia':["Mongolia","mongolia","MONGOLIA","Mongolia","Mongolie","Mongolia","Mongolei"],
				'montenegro':["Montenegro","montenegro","MONTENEGRO","Montenegro","Monténégro","Montenegro","Montenegro"],
				'montserrat':["Montserrat","montserrat","MONTSERRAT","Montserrat","Montserrat","Montserrat","Montserrat"],
				'morocco':["Morocco","morocco","MOROCCO","Marruecos","Maroc","Marocco","Marokko"],
				'mozambique':["Mozambique","mozambique","MOZAMBIQUE","Mozambique","Mozambique","Mozambico","Mosambik"],
				'myanmar':["Myanmar","myanmar","MYANMAR","Myanmar","Myanmar","Myanmar","Myanmar"],
				'namibia':["Namibia","namibia","NAMIBIA","Namibia","Namibie","Namibia","Namibia"],
				'nauru':["Nauru","nauru","NAURU","Nauru","Nauru","Nauru","Nauru"],
				'nepal':["Nepal","nepal","NEPAL","Nepal","Népal","Nepal","Nepal"],
				'netherlands':["Netherlands","netherlands","NETHERLANDS","Países Bajos","Pays-Bas","Olanda","Niederlande"],
				'netherlands':["antilles","Netherlands Antilles","netherlands antilles","NETHERLANDS ANTILLES","Antillas Holandesas","Antilles néerlandaises","Antille Olandesi","Niederländische Antillen"],
				'new':["caledonia","New Caledonia","new caledonia","NEW CALEDONIA","Nueva Caledonia","Nouvelle Calédonie","Nuova Caledonia","Neu-Kaledonien"],
				'new':["zealand","New Zealand","new zealand","NEW ZEALAND","Nueva Zelanda","Nouvelle-Zélande","Nuova Zelanda","Neuseeland"],
				'nicaragua':["Nicaragua","nicaragua","NICARAGUA","Nicaragua","Nicaragua","Nicaragua","Nicaragua"],
				'niger':["Niger","niger","NIGER","Níger","Niger","Niger","Niger"],
				'nigeria':["Nigeria","nigeria","NIGERIA","Nigeria","Nigeria","Nigeria","Nigeria"],
				'niue':["Niue","niue","NIUE","Niue","Niue","Niue","Niue"],
				'norfolk':["island","Norfolk Island","norfolk island","NORFOLK ISLAND","Isla Norfolk","l'ile de Norfolk","Norfolk Island","Norfolkinsel"],
				'northern':["mariana-islands","Northern Mariana Islands","northern mariana islands","NORTHERN MARIANA ISLANDS","Islas Marianas del Norte","Îles Mariannes du Nord","Isole Marianne settentrionali","Nördliche Marianneninseln"],
				'norway':["Norway","norway","NORWAY","Noruega","Norvège","Norvegia","Norwegen"],
				'oman':["Oman","oman","OMAN","Omán","Oman","Oman","Oman"],
				'pakistan':["Pakistan","pakistan","PAKISTAN","Pakistán","Pakistan","Pakistan","Pakistan"],
				'palau':["Palau","palau","PALAU","Palau","Palau","Palau","Palau"],
				'palestine':["Palestinian Territory","palestinian territory","PALESTINIAN TERRITORY","Territorio Palestino","Territoire Palestinien","Territori palestinesi","Palästinensisches Gebiet"],
				'panama':["Panama","panama","PANAMA","Panamá","Panama","Panama","Panama"],
				'papua':["new-guinea","Papua New Guinea","papua new guinea","PAPUA NEW GUINEA","Papúa Nueva Guinea","Papouasie Nouvelle Guinée","Papua Nuova Guinea","Papua Neu-Guinea"],
				'paraguay':["Paraguay","paraguay","PARAGUAY","Paraguay","Paraguay","Paraguay","Paraguay"],
				'peru':["Peru","peru","PERU","Perú","Pérou","Perù","Peru"],
				'philippines':["Philippines","philippines","PHILIPPINES","Filipinas","Philippines","Filippine","Philippinen"],
				'pitcairn':["Pitcairn","pitcairn","PITCAIRN","Pitcairn","Pitcairn","Pitcairn","Pitcairn"],
				'poland':["Poland","poland","POLAND","Polonia","Pologne","Polonia","Polen"],
				'portugal':["Portugal","portugal","PORTUGAL","Portugal","le Portugal","Portogallo","Portugal"],
				'puerto':["rico","Puerto Rico","puerto rico","PUERTO RICO","Puerto Rico","Porto Rico","Porto Rico","Puerto Rico"],
				'qatar':["Qatar","qatar","QATAR","Katar","Qatar","Qatar","Katar"],
				'kosovo':["Republic of Kosovo","republic of kosovo","REPUBLIC OF KOSOVO","República de Kosovo","République du Kosovo","Repubblica del Kosovo","Republik Kosovo"],
				'réunion':["Réunion","réunion","RÉUNION","Reunión","Réunion","Riunione","Wiedervereinigung"],
				'romania':["Romania","romania","ROMANIA","Rumania","Roumanie","Romania","Rumänien"],
				'russia':["Russian Federation","russian federation","RUSSIAN FEDERATION","Federación Rusa","Fédération Russe","Federazione Russa","Russische Föderation"],
				'rwanda':["Rwanda","rwanda","RWANDA","Ruanda","Rwanda","Ruanda","Ruanda"],
				'saint':["helena","Saint Helena","saint helena","SAINT HELENA","Santa Helena","Sainte-Hélène","Santa Helena","St. Helena"],
				'saint':["kitts-and-nevis","Saint Kitts and Nevis","saint kitts and nevis","SAINT KITTS AND NEVIS","Saint Kitts y Nevis","Saint-Christophe-et-Niévès","Saint Kitts e Nevis","St. Kitts und Nevis"],
				'saint':["lucia","Saint Lucia","saint lucia","SAINT LUCIA","Santa Lucía","Sainte-Lucie","Santa Lucia","St. Lucia"],
				'saint':["pierre-and-miquelon","Saint Pierre and Miquelon","saint pierre and miquelon","SAINT PIERRE AND MIQUELON","San Pedro y Miquelón","Saint-Pierre-et-Miquelon","Saint Pierre e Miquelon","Saint-Pierre und Miquelon"],
				'saint':["vincent-and-the-grenadines","Saint Vincent and Grenadines","saint vincent and grenadines","SAINT VINCENT AND GRENADINES","San Vicente y Granadinas","Saint-Vincent-et-Grenadines","Saint Vincent e Grenadine","St. Vincent und Grenadinen"],
				'saint':["barthélemy","Saint-Barthélemy","saint-barthélemy","SAINT-BARTHÉLEMY","San Bartolomé","Saint-Barthélemy","Saint-Barthélemy","Saint-Barthélemy"],
				'saint':["martin-french-part","Saint-Martin (French part)","saint-martin (french part)","SAINT-MARTIN (FRENCH PART)","San Martín (parte francesa)","Saint-Martin (partie française)","Saint-Martin (parte francese)","Saint-Martin (Französisch Teil)"],
				'samoa':["Samoa","samoa","SAMOA","Samoa","Samoa","Samoa","Samoa"],
				'san':["marino","San Marino","san marino","SAN MARINO","San Marino","Saint Marin","San Marino","San Marino"],
				'sao':["tome-and-principe","Sao Tome and Principe","sao tome and principe","SAO TOME AND PRINCIPE","Santo Tomé y Príncipe","Sao Tomé-et-Principe","Sao Tome e Principe","Sao Tome und Principe"],
				'saudi':["arabia","Saudi Arabia","saudi arabia","SAUDI ARABIA","Arabia Saudita","Arabie Saoudite","Arabia Saudita","Saudi Arabien"],
				'senegal':["Senegal","senegal","SENEGAL","Senegal","Sénégal","Senegal","Senegal"],
				'serbia':["Serbia","serbia","SERBIA","Serbia","Serbie","Serbia","Serbien"],
				'seychelles':["Seychelles","seychelles","SEYCHELLES","Seychelles","les Seychelles","Seychelles","Seychellen"],
				'sierra':["leone","Sierra Leone","sierra leone","SIERRA LEONE","Sierra Leone","Sierra Leone","Sierra Leone","Sierra Leone"],
				'singapore':["Singapore","singapore","SINGAPORE","Singapur","Singapour","Singapore","Singapur"],
				'slovakia':["Slovakia","slovakia","SLOVAKIA","Eslovaquia","Slovaquie","Slovacchia","Slowakei"],
				'slovenia':["Slovenia","slovenia","SLOVENIA","Eslovenia","Slovénie","Slovenia","Slowenien"],
				'solomon':["islands","Solomon Islands","solomon islands","SOLOMON ISLANDS","Islas Salomón","îles Salomon","Isole Salomone","Salomon-Inseln"],
				'somalia':["Somalia","somalia","SOMALIA","Somalia","Somalie","Somalia","Somalia"],
				'south':["africa","South Africa","south africa","SOUTH AFRICA","Sudáfrica","Afrique du Sud","Sud Africa","Südafrika"],
				'south':["georgia-and-the-south-sandwich-islands","South Georgia and the South Sandwich Islands","south georgia and the south sandwich islands","SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","Georgia del sur y las islas Sandwich del sur","Géorgie du Sud et les îles Sandwich du Sud","Georgia del Sud e isole Sandwich del Sud","Süd-Georgien und die südlichen Sandwich-Inseln"],
				'south':["sudan","South Sudan","south sudan","SOUTH SUDAN","Sudán del Sur","Soudan du sud","Sudan del Sud","Südsudan"],
				'spain':["Spain","spain","SPAIN","España","Espagne","Spagna","Spanien"],
				'sri':["lanka","Sri Lanka","sri lanka","SRI LANKA","Sri Lanka","Sri Lanka","Sri Lanka","Sri Lanka"],
				'sudan':["Sudan","sudan","SUDAN","Sudán","Soudan","Sudan","Sudan"],
				'suriname':["Suriname","suriname","SURINAME","Surinam","Suriname","Suriname","Suriname"],
				'svalbard':["and-jan-mayen-islands","Svalbard and Jan Mayen Islands","svalbard and jan mayen islands","SVALBARD AND JAN MAYEN ISLANDS","Svalbard y Jan Mayen","Spitzberg et Jan Mayen","Svalbard e Jan Mayen","Svalbard und Jan Mayen"],
				'swaziland':["Swaziland","swaziland","SWAZILAND","Swazilandia","Swaziland","Swaziland","Swasiland"],
				'sweden':["Sweden","sweden","SWEDEN","Suecia","Suède","Svezia","Schweden"],
				'switzerland':["Switzerland","switzerland","SWITZERLAND","Suiza","Suisse","Svizzera","Schweiz"],
				'syria':["Syrian Arab Republic (Syria)","syrian arab republic (syria)","SYRIAN ARAB REPUBLIC (SYRIA)","Siria (Siria)","République arabe syrienne (Syrie)","Siria (Siria)","Arabische Republik Syrien (Syrien)"],
				'taiwan':["Taiwan","taiwan","TAIWAN","Taiwán","Taïwan","Taiwan","Taiwan"],
				'tajikistan':["Tajikistan","tajikistan","TAJIKISTAN","Tayikistán","Tadjikistan","Tajikistan","Tadschikistan"],
				'tanzania':["Tanzania","tanzania","TANZANIA","Tanzania","Tanzanie","Tanzania","Tansania"],
				'thailand':["Thailand","thailand","THAILAND","Tailandia","Thaïlande","Tailandia","Thailand"],
				'timor':["leste","Timor-Leste","timor-leste","TIMOR-LESTE","Timor del Este","Timor-Leste","Timor Est","Timor-Leste"],
				'togo':["Togo","togo","TOGO","Ir","Aller","Andare","Gehen"],
				'tokelau':["Tokelau","tokelau","TOKELAU","Tokelau","Tokelau","Tokelau","Tokelau"],
				'tonga':["Tonga","tonga","TONGA","Tonga","Tonga","tonga","Tonga"],
				'trinidad':["and-tobago","Trinidad and Tobago","trinidad and tobago","TRINIDAD AND TOBAGO","Trinidad y Tobago","Trinité-et-Tobago","Trinidad e Tobago","Trinidad und Tobago"],
				'tunisia':["Tunisia","tunisia","TUNISIA","Túnez","Tunisie","Tunisia","Tunesien"],
				'turkey':["Turkey","turkey","TURKEY","pavo","dinde","tacchino","Truthahn"],
				'turkmenistan':["Turkmenistan","turkmenistan","TURKMENISTAN","Turkmenistán","Turkménistan","Turkmenistan","Turkmenistan"],
				'turks':["and-caicos-islands","Turks and Caicos Islands","turks and caicos islands","TURKS AND CAICOS ISLANDS","Islas Turcas y Caicos","îles Turques-et-Caïques","Isole Turks e Caicos","Turks- und Caicosinseln"],
				'tuvalu':["Tuvalu","tuvalu","TUVALU","Tuvalu","Tuvalu","Tuvalu","Tuvalu"],
				'uganda':["Uganda","uganda","UGANDA","Uganda","Ouganda","Uganda","Uganda"],
				'ukraine':["Ukraine","ukraine","UKRAINE","Ucrania","Ukraine","Ucraina","Ukraine"],
				'united':["arab-emirates","United Arab Emirates","united arab emirates","UNITED ARAB EMIRATES","Emiratos Árabes Unidos","Emirats Arabes Unis","Emirati Arabi Uniti","Vereinigte Arabische Emirate"],
				'united':["kingdom","United Kingdom","united kingdom","UNITED KINGDOM","Reino Unido","Royaume-Uni","Regno Unito","Großbritannien"],
				'united':["states","United States of America","united states of america","UNITED STATES OF AMERICA","Estados Unidos de America","les États-Unis d'Amérique","Stati Uniti d'America","vereinigte Staaten von Amerika"],
				'uruguay':["Uruguay","uruguay","URUGUAY","Uruguay","Uruguay","Uruguay","Uruguay"],
				'us':["minor-outlying-islands","US Minor Outlying Islands","us minor outlying islands","US MINOR OUTLYING ISLANDS","Islas periféricas menores de los Estados Unidos","Îles mineures éloignées des États-Unis","Stati Uniti Isole Minori","US Minor Outlying Islands"],
				'uzbekistan':["Uzbekistan","uzbekistan","UZBEKISTAN","Uzbekistán","Ouzbékistan","Uzbekistan","Usbekistan"],
				'vanuatu':["Vanuatu","vanuatu","VANUATU","Vanuatu","Vanuatu","Vanuatu","Vanuatu"],
				'venezuela':["Venezuela (Bolivarian Republic)","venezuela (bolivarian republic)","VENEZUELA (BOLIVARIAN REPUBLIC)","Venezuela (República Bolivariana)","Venezuela (République bolivarienne)","Venezuela (Repubblica Bolivariana)","Venezuela (Bolivarische Republik)"],
				'vietnam':["Viet Nam","viet nam","VIET NAM","Vietnam","Viet Nam","Viet Nam","Vietnam"],
				'virgin':["islands","Virgin Islands","virgin islands","VIRGIN ISLANDS","Islas Virgenes","Les iles vierges","Isole Vergini","Jungferninseln"],
				'wallis':["and-futuna-islands","Wallis and Futuna Islands","wallis and futuna islands","WALLIS AND FUTUNA ISLANDS","Wallis y Futuna","Wallis-et-Futuna","Isole Wallis e Futuna","Wallis und Futuna"],
				'western':["sahara","Western Sahara","western sahara","WESTERN SAHARA","Sahara Occidental","Sahara occidental","Sahara occidentale","Westsahara"],
				'yemen':["Yemen","yemen","YEMEN","Yemen","Yémen","yemen","Jemen"],
				'zambia':["Zambia","zambia","ZAMBIA","Zambia","Zambie","Zambia","Sambia"],
				'zimbabwe':["Zimbabwe","zimbabwe","ZIMBABWE","Zimbabue","Zimbabwe","Zimbabwe","Zimbabw"]
			}
def getCountryCode(country):
	for key in countries.keys():
		if country in countries[key]:
			return key
	return country