#Country key equivalence between Watsons existing (Country Entity Value/covid19api key) and spanish natural language. 
natural = {"afghanistan": "Afganistán",
"ala-aland-islands": "ALA Islas Aland",
"albania": "Albania",
"algeria": "Argelia",
"american-samoa": "Samoa Americana",
"andorra": "Andorra",
"angola": "Angola",
"anguilla": "Anguilla",
"antarctica": "Antártida",
"antigua-and-barbuda": "Antigua y Barbuda",
"argentina": "Argentina",
"armenia": "Armenia",
"aruba": "Aruba",
"australia": "Australia",
"austria": "Austria",
"azerbaijan": "Azerbaiyán",
"bahamas": "Bahamas",
"bahrain": "Bahrein",
"bangladesh": "Bangladesh",
"barbados": "Barbados",
"belarus": "Bielorrusia",
"belgium": "Bélgica",
"belize": "Belice",
"benin": "Benin",
"bermuda": "islas Bermudas",
"bhutan": "Bután",
"bolivia": "Bolivia",
"bosnia-and-herzegovina": "Bosnia y Herzegovina",
"botswana": "Botswana",
"bouvet-island": "Isla Bouvet",
"brazil": "Brasil",
"british-indian-ocean-territory": "Territorio Británico del Océano Índico",
"british-virgin-islands": "Islas Vírgenes Británicas",
"brunei": "Brunei Darussalam",
"bulgaria": "Bulgaria",
"burkina-faso": "Burkina Faso",
"burundi": "Burundi",
"cambodia": "Camboya",
"cameroon": "Camerún",
"canada": "Canadá",
"cape-verde": "Cabo Verde",
"cayman-islands": "Islas Caimán",
"central-african-republic": "República Centroafricana",
"chad": "Chad",
"chile": "Chile",
"china": "China",
"christmas-island": "Isla de Navidad",
"cocos-keeling-islands": "Cocos (Keeling)",
"colombia": "Colombia",
"comoros": "Comoras",
"congo-brazzaville": "Congo (Brazzaville)",
"congo-kinshasa": "Congo (Kinshasa)",
"cook-islands": "Islas Cook",
"costa-rica": "Costa Rica",
"cote-divoire": "Costa de Marfil",
"croatia": "Croacia",
"cuba": "Cuba",
"cyprus": "Chipre",
"czech-republic": "Republica checa",
"denmark": "Dinamarca",
"djibouti": "Djibouti",
"dominica": "dominica",
"dominican-republic": "República Dominicana",
"ecuador": "Ecuador",
"egypt": "Egipto",
"el-salvador": "El Salvador",
"equatorial-guinea": "Guinea Ecuatorial",
"eritrea": "Eritrea",
"estonia": "Estonia",
"ethiopia": "Etiopía",
"falkland-islands-malvinas": "Islas Malvinas (Falkland)",
"faroe-islands": "Islas Faroe",
"fiji": "Fiji",
"finland": "Finlandia",
"france": "Francia",
"french-guiana": "Guayana francés",
"french-polynesia": "Polinesia francés",
"french-southern-territories": "Territorios Franceses del Sur",
"gabon": "Gabón",
"gambia": "Gambia",
"georgia": "Georgia",
"germany": "Alemania",
"ghana": "Ghana",
"gibraltar": "Gibraltar",
"greece": "Grecia",
"greenland": "Groenlandia",
"grenada": "Granada",
"guadeloupe": "Guadalupe",
"guam": "Guam",
"guatemala": "Guatemala",
"guernsey": "Guernesey",
"guinea": "Guinea",
"guinea-bissau": "Guinea-Bissau",
"guyana": "Guayana",
"haiti": "Haití",
"heard-and-mcdonald-islands": "Islas Heard y McDonald",
"holy-see-vatican-city-state": "Santa Sede (Ciudad del Vaticano)",
"honduras": "Honduras",
"hong-kong-sar-china": "Hong Kong",
"hungary": "Hungría",
"iceland": "Islandia",
"india": "India",
"indonesia": "Indonesia",
"iran": "Irán",
"iraq": "Irak",
"ireland": "Irlanda",
"isle-of-man": "Isla del hombre",
"israel": "Israel",
"italy": "Italia",
"jamaica": "Jamaica",
"japan": "Japón",
"jersey": "Jersey",
"jordan": "Jordán",
"kazakhstan": "Kazajstán",
"kenya": "Kenia",
"kiribati": "Kiribati",
"korea-north": "Corea (del Norte)",
"korea-south": "Corea del Sur)",
"kuwait": "Kuwait",
"kyrgyzstan": "Kirguizistán",
"lao-pdr": "República Democrática Popular Lao",
"latvia": "Letonia",
"lebanon": "Líbano",
"lesotho": "Lesoto",
"liberia": "Liberia",
"libya": "Libia",
"liechtenstein": "Liechtenstein",
"lithuania": "Lituania",
"luxembourg": "Luxemburgo",
"macao-sar-china": "macao",
"macedonia": "macedonia",
"madagascar": "Madagascar",
"malawi": "Malawi",
"malaysia": "Malasia",
"maldives": "Maldivas",
"mali": "mali",
"malta": "Malta",
"marshall-islands": "Islas Marshall",
"martinique": "Martinica",
"mauritania": "Mauritania",
"mauritius": "Isla mauricio",
"mayotte": "Mayotte",
"mexico": "México",
"micronesia": "micronesia",
"moldova": "Moldavia",
"monaco": "Mónaco",
"mongolia": "Mongolia",
"montenegro": "Montenegro",
"montserrat": "Montserrat",
"morocco": "Marruecos",
"mozambique": "Mozambique",
"myanmar": "Myanmar",
"namibia": "Namibia",
"nauru": "Nauru",
"nepal": "Nepal",
"netherlands": "Países Bajos",
"netherlands-antilles": "Antillas Holandesas",
"new-caledonia": "Nueva Caledonia",
"new-zealand": "Nueva Zelanda",
"nicaragua": "Nicaragua",
"niger": "Níger",
"nigeria": "Nigeria",
"niue": "Niue",
"norfolk-island": "Isla Norfolk",
"northern-mariana-islands": "Islas Marianas del Norte",
"norway": "Noruega",
"oman": "Omán",
"pakistan": "Pakistán",
"palau": "Palau",
"palestine": "Territorio Palestino",
"panama": "Panamá",
"papua-new-guinea": "Papúa Nueva Guinea",
"paraguay": "Paraguay",
"peru": "Perú",
"philippines": "Filipinas",
"pitcairn": "Pitcairn",
"poland": "Polonia",
"portugal": "Portugal",
"puerto-rico": "Puerto Rico",
"qatar": "Katar",
"kosovo": "República de Kosovo",
"réunion": "Reunión",
"romania": "Rumania",
"russia": "Federación Rusa",
"rwanda": "Ruanda",
"saint-helena": "Santa Helena",
"saint-kitts-and-nevis": "Saint Kitts y Nevis",
"saint-lucia": "Santa Lucía",
"saint-pierre-and-miquelon": "San Pedro y Miquelón",
"saint-vincent-and-the-grenadines": "San Vicente y Granadinas",
"saint-barthélemy": "San Bartolomé",
"saint-martin-french-part": "San Martín (parte francesa)",
"samoa": "Samoa",
"san-marino": "San Marino",
"sao-tome-and-principe": "Santo Tomé y Príncipe",
"saudi-arabia": "Arabia Saudita",
"senegal": "Senegal",
"serbia": "Serbia",
"seychelles": "Seychelles",
"sierra-leone": "Sierra Leone",
"singapore": "Singapur",
"slovakia": "Eslovaquia",
"slovenia": "Eslovenia",
"solomon-islands": "Islas Salomón",
"somalia": "Somalia",
"south-africa": "Sudáfrica",
"south-georgia-and-the-south-sandwich-islands": "Georgia del sur y las islas Sandwich del sur",
"south-sudan": "Sudán del Sur",
"spain": "España",
"sri-lanka": "Sri Lanka",
"sudan": "Sudán",
"suriname": "Surinam",
"svalbard-and-jan-mayen-islands": "Svalbard y Jan Mayen",
"swaziland": "Swazilandia",
"sweden": "Suecia",
"switzerland": "Suiza",
"syria": "Siria (Siria)",
"taiwan": "Taiwán",
"tajikistan": "Tayikistán",
"tanzania": "Tanzania",
"thailand": "Tailandia",
"timor-leste": "Timor del Este",
"togo": "Ir",
"tokelau": "Tokelau",
"tonga": "Tonga",
"trinidad-and-tobago": "Trinidad y Tobago",
"tunisia": "Túnez",
"turkey": "pavo",
"turkmenistan": "Turkmenistán",
"turks-and-caicos-islands": "Islas Turcas y Caicos",
"tuvalu": "Tuvalu",
"uganda": "Uganda",
"ukraine": "Ucrania",
"united-arab-emirates": "Emiratos Árabes Unidos",
"united-kingdom": "Reino Unido",
"united-states": "Estados Unidos de America",
"uruguay": "Uruguay",
"us-minor-outlying-islands": "Islas periféricas menores de los Estados Unidos",
"uzbekistan": "Uzbekistán",
"vanuatu": "Vanuatu",
"venezuela": "Venezuela (República Bolivariana)",
"vietnam": "Vietnam",
"virgin-islands": "Islas Virgenes",
"wallis-and-futuna-islands": "Wallis y Futuna",
"western-sahara": "Sahara Occidental",
"yemen": "Yemen",
"zambia": "Zambia",
"zimbabwe": "Zimbabue"}